spring:
  cloud:
    gateway:
      routes:
        - id: test_route
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu


        - id: qq_route
          uri: https://www.qq.com
          predicates:
            - Query=url,qq

        ########################  gulimall-product 路由转发重写规则   ########################
        - id: product_route
          uri: lb://gulimall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /$\{segment}

        ########################  renren-fast 路由转发重写规则   ########################
        - id: admin_route
          #          lb://   表示loadBalance 负载均衡
          uri: lb://renren-fast
          predicates:
            #         前端项目全部带上  api  前缀
            ###############   一定要注意  这个路径  大范围会把小范围的路径过滤掉  此时应该调整位置
            - Path=/api/**
          filters:
            #          路径重写  表示  将   /api/**  路径  全部重写为   /renren-fast/**
            - RewritePath=/api/(?<segment>/?.*), /renren-fast/$\{segment}